routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();


/**
 * -----------------------------------------------------------------------------
 * Public route area
 * -----------------------------------------------------------------------------
 */
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', function () {
    return view('welcome');
});
Route::get('/verification/list', 'VerificationController@getReviewed');
Route::get('/verification/list/unreviewed', 'VerificationController@getUnreviewed');
Route::get('/verification/review-result/{id}', 'VerificationController@showReviewResult');
Route::get('/verificator/list', 'Verificator\VerificatorController@all')->name('public.verificator.list');
Route::get('/verificator/{id}', 'Verificator\VerificatorController@profile')->name('public.verificator.profile');
Route::get('/verificator/{id}/biography', 'Verificator\VerificatorController@showBiography')->name('show_verificator_biography');
Route::get('/user/{id}', 'UserController@profile');
Route::get('/verification/detail/{id}', 'VerificationController@detail')->name('public.verification.detail');

/**
 * -----------------------------------------------------------------------------
 * Logged In User route area
 * -----------------------------------------------------------------------------
 */
Route::middleware('auth')->group(function() {
    Route::prefix('user')->group(function() {
        // TODO: pakai form POST method biar aman (ref: https://laracasts.com/discuss/channels/laravel/laravel-53-logout-methodnotallowed)
        Route::get('/logout', 'Auth\LoginController@logout');
        Route::get('/change', function() {
            return view('user.change', ['user' => Auth::user()]);
        });
        Route::post('/change', 'UserController@change');
        Route::post('/delete', 'UserController@delete')->name('user_delete');
    });

    Route::prefix('verification')->group(function() {
        Route::get('new-request/image-based', function() {
            return view('verification.new_request_image_based');
        });
        Route::get('new-request/link-based', function() {
            return view('verification.new_request_link_based');
        });
        Route::post('new-request/image-based', 'VerificationController@addVerificationRequestImagesBased')->name('new_request_image_based');
        Route::post('link-based', 'VerificationController@addVerificationRequestLinkBased')->name('new_request_link_based');

        Route::get('delete/{id}', 'VerificationController@delete')->name('verification.delete');
    });
});



/**
 * -----------------------------------------------------------------------------
 * Verificator route area
 * -----------------------------------------------------------------------------
 */
Route::namespace('Verificator')->prefix('verificator')->group(function() {
        Route::middleware('auth_verificator')->group(function() {
            Route::get('logout', 'Auth\LoginController@logout');
            Route::get('/change', function() {
                return view('verificator.change', ['verificator' => Auth::guard('web_verificator')->user()]);
            });
            Route::post('/change', 'VerificatorController@change');

            Route::get('review/form/{verification_item_id}', 'ReviewController@showForm');
            Route::post('review/form/{verification_item_id}', 'ReviewController@saveReview');
        });

        Route::middleware('verificator_guest')->group(function() {
            Route::get('login', 'Auth\LoginController@showLoginForm');
            Route::post('login', 'Auth\LoginController@login')->name('verificator.login');
        });
});

/**
 * -----------------------------------------------------------------------------
 * Admin route area
 * -----------------------------------------------------------------------------
 */
Route::prefix('admin')->group(function(){
    Route::middleware('auth_admin')
        ->namespace('Admin')
        ->group(function() {
            Route::get('logout', 'Auth\LoginController@logout');
            Route::get('/change', function() {
                return view('admin.change', ['admin' => Auth::guard('web_admin')->user()]);
            });
            Route::post('/change', 'AdminController@change');
            Route::get('/dashboard', function() {
                return view('admin.dashboard');
            })->name('admin.dashboard');
            Route::get('/admin-list', 'AdminController@all')->name('admin.list');
            Route::get('/create-new', function() {
                return view('admin.create-new');
            })->name('admin.create-new');
            Route::post('/create-new', 'AdminController@create')->name('create_admin');
            Route::get('/verification-list', 'AdminController@getVerificationList')->name('admin.verification-list');
            Route::get('/change', function() {
                return view('admin.change', ['admin' => Auth::guard('web_admin')->user()]);
            })->name('admin.change');
            Route::post('/change', 'AdminController@change');
        });

    Route::middleware('auth_admin')
        ->group(function() {
            Route::get('/user-list', 'UserController@all')->name('admin.user-list');
            Route::post('/user/delete/{id}', 'UserController@delete');

            Route::get('/verificator-list', 'Verificator\VerificatorController@all')->name('admin.verificator-list');
            Route::get('/verificator/create', function() {
                return view('admin.create-verificator');
            })->name('admin.verificator-create');
            Route::post('/verificator/create', 'Verificator\VerificatorController@create')->name('create_verificator');
            Route::post('/verificator/delete/{id}', 'Verificator\VerificatorController@delete');
            Route::get('/verificator/{id}/biography/create', 'Verificator\VerificatorController@createBiography');
            Route::post('/verificator/{id}/biography/create', 'Verificator\VerificatorController@saveBiography')->name('create_verificator_biography');

            Route::get('/verification/detail/{id}', 'VerificationController@detail');
            Route::get('/verification/delete/{id}', 'VerificationController@delete');
        });

    Route::middleware('admin_guest')
        ->namespace('Admin')
        ->group(function() {
            Route::get('login', 'Auth\LoginController@showLoginForm');
            Route::post('login', 'Auth\LoginController@login')->name('admin.login');
        });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'photo',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    const PHOTO_PROFILE_DIR = 'storage/user_photo_profile';
    const PHOTO_DEFAULT     = 'storage/images/default_photo.svg';

    public function verification_items()
    {
        return $this->hasMany('App\VerificationItem')
                        ->orderBy('created_at', 'asc');
    }

    public function getPhotoPathAttribute()
    {
        if (!$this->photo) {
            return self::PHOTO_DEFAULT;
        }
        return self::PHOTO_PROFILE_DIR.'/'.$this->photo;
    }
}

resources/views/admin/admin-list.blade.php
@extends('layouts.admin')

@section('title', 'Admin Lists')

@section('content')
<div>
    <div class="ctn-main-font ctn-min-color ctn-standar padding-20px">Admin Lists</div>
    <table border="1">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Tanggal Dibuat</th>
            <th>Foto</th>
        </tr>
        @foreach ($admins as $admin)
        <tr>
            <td>{{ $admin->id }}</td>
            <td>{{ $admin->name }}</td>
            <td>{{ $admin->email }}</td>
            <td>{{ $admin->created_at }}</td>
            <td><img width="28" height="28" src="{{ asset($admin->photo_path) }}" alt="foto pengguna"></td>
        </tr>
        @endforeach
    </table>
    {{ $admins->links() }}
</div>
@endsection

resources/views/admin/change.blade.php
@extends('layouts.admin')

@section('title', 'Change account')

@section('content')
<script type="text/javascript">
    $(function () {
        var imagesPreview = function (input, place, place2 = '') {
            if (input.files) {
                var reader = new FileReader();  
                reader.onload = function (event) {
                    $(place).css('background-image', 'url('+event.target.result+')');
                }
                $(place2).html('Photo changed (not saved)');
                reader.readAsDataURL(input.files[0]);
            } else {
                $(place2).html('Please select a file');
            }
        };
        $('#photo-profile-field').on('change', function () {
            imagesPreview(this, '#image-preview', '#image-message');
        });
    })
</script>

<div class="login-container lg-big-width">
    <div class="ctn-main-font ctn-min-color ctn-standar padding-20px">{{ __('Edit Account') }}</div>
    <div class="lc-place">
        <form
            action="{{ url()->full() }}"
            method="post"
            enctype="multipart/form-data">
            @csrf
            <div class="lc-block">
                <div for="email" class="ctn-main-font ctn-min-color ctn-16px">
                    Public Informations
                </div>
            </div>
            <div class="lc-block">
                <div for="email" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">{{ __('Profile Picture') }}</div>
                <div>
                    <div class="padding-bottom-5px">
                        <div id="image-preview" class="image image-200px image-radius" style="background-image: url({{ asset($admin->photo_path) }})"></div>
                        <div id="image-message" class="ctn-main-font ctn-err-color ctn-14px ctn-thin padding-top-10px"></div>
                    </div>
                    <input id="photo-profile-field" type="file" name="photo">
                </div>
            </div>
            <div class="lc-block">
                <div for="email" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">{{ __('Name') }}</div>
                <div>
                    <input type="text" name="name" class="txt txt-primary-color" value="{{ $admin->name }}" required>
                </div>
            </div>
            <div class="lc-block">
                <div for="email" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">{{ __('Email') }}</div>
                <div>
                    <input type="email" name="email" class="txt txt-primary-color" value="{{ $admin->email }}" required="true">
                </div>
            </div>
            <div class="padding-10px"></div>
            <div class="lc-block">
                <div for="email" class="ctn-main-font ctn-min-color ctn-16px">
                    Private Informations
                </div>
            </div>
            <div class="lc-block">
                <div for="email" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">
                    Old Password
                </div>
                <div>
                    <input type="password" name="old_password" class="txt txt-primary-color">
                </div>
            </div>
            <div class="lc-block">
                <div for="email" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">
                    New Password
                </div>
                <div>
                    <input type="password" name="new_password" class="txt txt-primary-color">
                </div>
            </div>
            <div class="lc-block">
                <div for="email" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">
                    Confirm Password
                </div>
                <div>
                    <input type="password" name="confirm_password" class="txt txt-primary-color">
                </div>
            </div>
            <div class="lc-block">
                <div class="lc-right">
                    <input type="submit" name="submit" class="btn btn-main-color" value="Save Changed">
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/create-new.blade.php
@extends('layouts.admin')
@section('title', 'Create new admin')
@section('content')
<div class="login-container">
    <div class="ctn-main-font ctn-min-color ctn-standar padding-20px">{{ __('Create Admin Account') }}</div>
    <div class="lc-place">
        <form method="POST" action="{{ route('create_admin') }}">
            @csrf
            <div class="lc-block">
                <div for="name" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">{{ __('Name') }}</div>
                <div>
                    <input id="name" type="text" class="txt txt-primary-color form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>
                    @if ($errors->has('name'))
                        <div class="ctn-main-font ctn-err-color ctn-14px ctn-thin">
                            {{ $errors->first('name') }}
                        </div>
                    @endif
                </div>
            </div>
            <div class="lc-block">
                <div for="email" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">{{ __('E-Mail Address') }}</div>
                <div>
                    <input id="email" type="email" class="txt txt-primary-color form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>
                    @if ($errors->has('email'))
                        <div class="ctn-main-font ctn-err-color ctn-14px ctn-thin">
                            {{ $errors->first('email') }}
                        </div>
                    @endif
                </div>
            </div>
            <div class="lc-block">
                <div for="password" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">{{ __('Password') }}</div>
                <div>
                    <input id="password" type="password" class="txt txt-primary-color form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>
                    @if ($errors->has('password'))
                        <div class="ctn-main-font ctn-err-color ctn-14px ctn-thin">
                            {{ $errors->first('password') }}
                        </div>
                    @endif
                </div>
            </div>
            <div class="lc-block">
                <div for="password-confirm" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">{{{ __('Confirm Password') }}}</div>
                <div>
                    <input id="password-confirm" type="password" class="txt txt-primary-color" name="password_confirmation" required>
                </div>
            </div>
            <div class="lc-block">
                <div class="lc-right">
                    <button type="submit" class="btn btn-main-color">
                        {{ __('Create') }}
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/create-verificator-biography.blade.php
@extends('layouts.admin')
@section('title', 'Create Verificator Biography')
@section('content')
    <h2>Biografi {{ $verificator->name }}</h3>

    <form action="{{ route('create_verificator_biography', ['id' => $verificator->id]) }}" method="post">
        @csrf
        <textarea id="biograhpy-field" name="biography" cols="50" rows="20"></textarea>
        <button>Simpan</button>
    </form>
@endsection

resources/views/admin/create-verificator.blade.php
@extends('layouts.admin')
@section('title', 'Create new Verificator')
@section('content')
<div class="login-container">
    <div class="ctn-main-font ctn-min-color ctn-standar padding-20px">{{ __('Create Verificator Account') }}</div>
    <div class="lc-place">
        <form method="POST" action="{{ route('create_verificator') }}">
            @csrf
            <div class="lc-block">
                <div for="name" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">{{ __('Name') }}</div>
                <div>
                    <input id="name" type="text" class="txt txt-primary-color form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required autofocus>
                    @if ($errors->has('name'))
                        <div class="ctn-main-font ctn-err-color ctn-14px ctn-thin">
                            {{ $errors->first('name') }}
                        </div>
                    @endif
                </div>
            </div>
            <div class="lc-block">
                <div for="email" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">{{ __('E-Mail Address') }}</div>
                <div>
                    <input id="email" type="email" class="txt txt-primary-color form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>
                    @if ($errors->has('email'))
                        <div class="ctn-main-font ctn-err-color ctn-14px ctn-thin">
                            {{ $errors->first('email') }}
                        </div>
                    @endif
                </div>
            </div>
            <div class="lc-block">
                <div for="password" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">{{ __('Password') }}</div>
                <div>
                    <input id="password" type="password" class="txt txt-primary-color form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>
                    @if ($errors->has('password'))
                        <div class="ctn-main-font ctn-err-color ctn-14px ctn-thin">
                            {{ $errors->first('password') }}
                        </div>
                    @endif
                </div>
            </div>
            <div class="lc-block">
                <div for="password-confirm" class="ctn-main-font ctn-min-color ctn-14px ctn-thin">{{{ __('Confirm Password') }}}</div>
                <div>
                    <input id="password-confirm" type="password" class="txt txt-primary-color" name="password_confirmation" required>
                </div>
            </div>
            <div class="lc-block">
                <div class="lc-right">
                    <button type="submit" class="btn btn-main-color">
                        {{ __('Create') }}
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')
@section('title', 'Dashboard')
@section('content')
<div>
    <div class="ctn-main-font ctn-min-color ctn-standar padding-20px">Dashboard</div>
</div>
@endsection

resources/views/admin/user-list.blade.php
@extends('layouts.admin')

@section('title', 'User Lists')

@section('content')
<div>
    <div class="ctn-main-font ctn-min-color ctn-standar padding-20px">User Lists</div>
    <table border="1">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Tanggal Bergabung</th>
            <th>Foto</th>
            <th>Aksi</th>
        </tr>
        @foreach ($users as $user)
        <tr>
            <td>{{ $user->id }}</td>
            <td>{{ $user->name }}</td>
            <td>{{ $user->email }}</td>
            <td>{{ $user->created_at }}</td>
            <td><img width="28" height="28" src="{{ asset($user->photo_path) }}" alt="foto pengguna"></td>
            <td><a href="{{ action('UserController@profile', ['id' => $user->id])}}">Lihat Profil</a></td>
        </tr>
        @endforeach
    </table>
    {{ $users->links() }}
</div>
@endsection

resources/views/admin/verification-list.blade.php
@extends('layouts.admin')

@section('title', 'Verification Lists')

@section('content')
<div>
    <div class="ctn-main-font ctn-min-color ctn-standar padding-20px">Verification Lists</div>
    <div class="list">
        @foreach ($verification_items as $verification_item)
            @include('main.card-verification')
        @endforeach

        {{ $verification_items->links() }}
    </div>
</div>
@endsection

resources/views/admin/verificator-list.blade.php
@extends('layouts.admin')

@section('title', 'Verificator Lists')

@section('content')
<div>
    <div class="ctn-main-font ctn-min-color ctn-standar padding-20px">Verificator Lists</div>
    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Tanggal Dibuat</th>
            <th>Foto</th>
            <th>Aksi</th>
        </tr>
        @foreach ($verificators as $verificator)
        <tr>
            <td>{{ $verificator->id }}</td>
            <td>{{ $verificator->name }}</td>
            <td>{{ $verificator->email }}</td>
            <td>{{ $verificator->created_at }}</td>
            <td><img width="28" height="28" src="{{ asset($verificator->photo_path) }}" alt="foto pengguna"></td>
            <td><a href="{{ action('Verificator\VerificatorController@profile', ['id' => $verificator->id])}}">Lihat Profil</a></td>
        </tr>
        @endforeach
    </table>
    {{ $verificators->links() }}
</div>
@endsection